//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Group_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scores
    {
        public int Id { get; set; }
        public string PlayerName { get; set; }
        public System.DateTime QuizDate { get; set; }
        public int QuizScore { get; set; }
        public string QuizType { get; set; }
    }
}
